# Generated by Django 4.0 on 2021-12-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAINpageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=30)),
                ('buttonHeading', models.CharField(max_length=30)),
                ('intro_pic', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
