# Generated by Django 4.0 on 2021-12-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpagecontent',
            old_name='Heading',
            new_name='Heading1',
        ),
        migrations.AddField(
            model_name='mainpagecontent',
            name='Heading2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
